=== Anh-Us/TH_XML_NguyenLeNhaAnh/buoi_04_NguyenLeNhaAnh/bai3/quanan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://example.com/quanan"
  xmlns="http://example.com/quanan"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  
  <xs:simpleType name="Ten10">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Ten50">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="UsernameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="6"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PasswordType">
    <xs:restriction base="xs:string">
      <xs:minLength value="10"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PhoneDigits">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{9,11}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GenderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Nam"/>
      <xs:enumeration value="Nu"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Money">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:fractionDigits value="0"/>
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="SoHDCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="HD\d{3}"/>
    </xs:restriction>
  </xs:simpleType>

  

  <xs:element name="QUANAN">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="BANs" type="BANsType"/>
        <xs:element name="NHANVIENs" type="NHANVIENsType"/>
        <xs:element name="MONs" type="MONsType"/>
        <xs:element name="HOADONs" type="HOADONsType"/>
        <xs:element name="CTHDs" type="CTHDsType"/>
      </xs:sequence>
    </xs:complexType>

    
    <xs:key name="BAN_pk">
      <xs:selector xpath="BANs/BAN"/>
      <xs:field xpath="@tenban"/>
    </xs:key>

    <xs:key name="NHANVIEN_pk">
      <xs:selector xpath="NHANVIENs/NHANVIEN"/>
      <xs:field xpath="@manv"/>
    </xs:key>

    <xs:key name="MON_pk">
      <xs:selector xpath="MONs/MON"/>
      <xs:field xpath="@mamon"/>
    </xs:key>

    <xs:key name="HOADON_pk">
      <xs:selector xpath="HOADONs/HOADON"/>
      <xs:field xpath="@sohd"/>
    </xs:key>

    
    <xs:keyref name="HOADON_to_BAN_fk" refer="BAN_pk">
      <xs:selector xpath="HOADONs/HOADON"/>
      <xs:field xpath="BanRef"/>
    </xs:keyref>

    <xs:keyref name="HOADON_to_NHANVIEN_fk" refer="NHANVIEN_pk">
      <xs:selector xpath="HOADONs/HOADON"/>
      <xs:field xpath="LapHD"/>
    </xs:keyref>

    <xs:keyref name="CTHD_to_HOADON_fk" refer="HOADON_pk">
      <xs:selector xpath="CTHDs/CTHD"/>
      <xs:field xpath="@sohdRef"/>
    </xs:keyref>

    <xs:keyref name="CTHD_to_MON_fk" refer="MON_pk">
      <xs:selector xpath="CTHDs/CTHD"/>
      <xs:field xpath="@mamonRef"/>
    </xs:keyref>
  </xs:element>

  
  <xs:complexType name="BANsType">
    <xs:sequence>
      <xs:element name="BAN" type="BANType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BANType">
    <xs:sequence>
      <xs:element name="SoBan" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="tenban" type="Ten10" use="required"/>
  </xs:complexType>

  
  <xs:complexType name="NHANVIENsType">
    <xs:sequence>
      <xs:element name="NHANVIEN" type="NHANVIENType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NHANVIENType">
    <xs:sequence>
      <xs:element name="TenNV" type="Ten50"/>
      <xs:element name="SDT" type="PhoneDigits"/>
      <xs:element name="DiaChi" type="xs:string"/>
      <xs:element name="GioiTinh" type="GenderType"/>
      <xs:element name="Username" type="UsernameType"/>
      <xs:element name="Password" type="PasswordType"/>
    </xs:sequence>
    <xs:attribute name="manv" type="Ten10" use="required"/>
  </xs:complexType>

  
  <xs:complexType name="MONsType">
    <xs:sequence>
      <xs:element name="MON" type="MONType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="MONType">
    <xs:sequence>
      <xs:element name="TenMon" type="Ten50"/>
      <xs:element name="Gia" type="Money"/>
    </xs:sequence>
    <xs:attribute name="mamon" type="Ten10" use="required"/>
  </xs:complexType>

  
  <xs:complexType name="HOADONsType">
    <xs:sequence>
      <xs:element name="HOADON" type="HOADONType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="HOADONType">
    <xs:sequence>
      <xs:element name="NgayLap" type="xs:date"/>
      <xs:element name="TongTien" type="Money"/>
      <xs:element name="BanRef" type="Ten10"/>
      <xs:element name="LapHD" type="Ten10"/>
    </xs:sequence>
    <xs:attribute name="sohd" type="SoHDCode" use="required"/>
  </xs:complexType>

  
  <xs:complexType name="CTHDsType">
    <xs:sequence>
      <xs:element name="CTHD" type="CTHDType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CTHDType">
    <xs:sequence>
      <xs:element name="SoLuong" type="xs:positiveInteger"/>
    </xs:sequence>
    <xs:attribute name="sohdRef" type="SoHDCode" use="required"/>
    <xs:attribute name="mamonRef" type="Ten10" use="required"/>
  </xs:complexType>

</xs:schema>

=== Anh-Us/TH_XML_NguyenLeNhaAnh/buoi_04_NguyenLeNhaAnh/bai3/quanan.xml
<?xml version="1.0" encoding="UTF-8"?>
<QUANAN
    xmlns="http://example.com/quanan"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.com/quanan quanan.xsd">

  
  <BANs>
    <BAN tenban="B01">
        <SoBan>1</SoBan>
    </BAN>
    <BAN tenban="B02">
        <SoBan>2</SoBan>
    </BAN>
    <BAN tenban="B03">
        <SoBan>3</SoBan>
    </BAN>
    <BAN tenban="B04">
        <SoBan>4</SoBan>
    </BAN>
    <BAN tenban="B05">
        <SoBan>5</SoBan>
    </BAN>
  </BANs>

  
  <NHANVIENs>
    <NHANVIEN manv="NV01">
      <TenNV>Nguyen Le Nha Anh</TenNV>
      <SDT>0901234567</SDT>
      <DiaChi>12 Nguyen Trai</DiaChi>
      <GioiTinh>Nu</GioiTinh>
      <Username>nhaanhanv</Username>
      <Password>Pass2025_01</Password>
    </NHANVIEN>

    <NHANVIEN manv="NV02">
      <TenNV>Nguyen Minh Khoa</TenNV>
      <SDT>0912345678</SDT>
      <DiaChi>34 Ly Thuong Kiet</DiaChi>
      <GioiTinh>Nam</GioiTinh>
      <Username>khoatran01</Username>
      <Password>StrongPwd2025</Password>
    </NHANVIEN>

    <NHANVIEN manv="NV03">
      <TenNV>Trinh Bao Khang</TenNV>
      <SDT>0987654321</SDT>
      <DiaChi>56 CMT8</DiaChi>
      <GioiTinh>Nu</GioiTinh>
      <Username>quynhanh07</Username>
      <Password>QAnhsecure10</Password>
    </NHANVIEN>

    <NHANVIEN manv="NV04">
      <TenNV>Tran Gia Bao</TenNV>
      <SDT>0931122334</SDT>
      <DiaChi>78 Vo Van Tan</DiaChi>
      <GioiTinh>Nam</GioiTinh>
      <Username>lelonghh</Username>
      <Password>Long2025safe</Password>
    </NHANVIEN>

    <NHANVIEN manv="NV05">
      <TenNV>Nguyen Phat Tai</TenNV>
      <SDT>0977332211</SDT>
      <DiaChi>90 Hai Ba Trung</DiaChi>
      <GioiTinh>Nu</GioiTinh>
      <Username>mylinhdo99</Username>
      <Password>DoMyLinh2025</Password>
    </NHANVIEN>
  </NHANVIENs>


  
  <MONs>
    <MON mamon="M01">
        <TenMon>Pho bo</TenMon>
        <Gia>45000</Gia>
    </MON>
    <MON mamon="M02">
        <TenMon>Bun cha</TenMon>
        <Gia>50000</Gia>
    </MON>
    <MON mamon="M03">
        <TenMon>Banh mi thit</TenMon>
        <Gia>25000</Gia>
    </MON>
    <MON mamon="M04">
        <TenMon>Ca phe sua</TenMon>
        <Gia>30000</Gia>
    </MON>
    <MON mamon="M05">
        <TenMon>Tra dao</TenMon>
        <Gia>28000</Gia>
    </MON>
  </MONs>

  
  <HOADONs>
    <HOADON sohd="HD001">
        <NgayLap>2025-10-01</NgayLap>
        <TongTien>128000</TongTien>
        <BanRef>B01</BanRef>
        <LapHD>NV01</LapHD>
    </HOADON>
    <HOADON sohd="HD002">
        <NgayLap>2025-10-01</NgayLap>
        <TongTien>95000</TongTien>
        <BanRef>B02</BanRef>
        <LapHD>NV02</LapHD>
    </HOADON>
    <HOADON sohd="HD003">
        <NgayLap>2025-10-02</NgayLap>
        <TongTien>155000</TongTien>
        <BanRef>B03</BanRef>
        <LapHD>NV03</LapHD>
    </HOADON>
    <HOADON sohd="HD004">
        <NgayLap>2025-10-02</NgayLap>
        <TongTien>73000</TongTien>
        <BanRef>B04</BanRef>
        <LapHD>NV04</LapHD>
    </HOADON>
    <HOADON sohd="HD005">
        <NgayLap>2025-10-03</NgayLap>
        <TongTien>102000</TongTien>
        <BanRef>B05</BanRef>
        <LapHD>NV05</LapHD>
    </HOADON>
  </HOADONs>


  
  <CTHDs>
    <CTHD sohdRef="HD001" mamonRef="M01">
        <SoLuong>1</SoLuong>
    </CTHD>
    <CTHD sohdRef="HD001" mamonRef="M04">
        <SoLuong>2</SoLuong>
    </CTHD>
    <CTHD sohdRef="HD002" mamonRef="M02">
        <SoLuong>1</SoLuong>
    </CTHD>
    <CTHD sohdRef="HD003" mamonRef="M03">
        <SoLuong>2</SoLuong>
    </CTHD>
    <CTHD sohdRef="HD004" mamonRef="M05">
        <SoLuong>1</SoLuong>
    </CTHD>
  </CTHDs>

</QUANAN>
